<a href="https://colab.research.google.com/github/masiDaniel/DataAnalysis/blob/main/project_with_udemy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas

df = pandas.read_excel('/project_data.xlsx')

In [ ]:
print(df)

           itemid    shopid                                  item_name  \
0         1925574    210000                      Golden mobile numbers
1         1925617    210000                      Golden mobile numbers
2          943600    210000                      Golden Mobile Numbers
3         1064405    210000                      Golden Mobile Numbers
4        20046620    760000               101% AUTHENTIC BASEBALL CAPS
...           ...       ...                                        ...
464428  517929442  13744999  Women Back Brest Dress Package Hips Dress
464429  490461243  13744999     Heart Alloy Pendant Necklace for women
464430  494272761  13744999     Heart Alloy Pendant Necklace for women
464431  259494170  13744999    Women Mid Elastic Waist Straight Shorts
464432  314558812  13744999    Women Mid Elastic Waist Straight Shorts

                                         item_description  \
0       Unregistered prepaid cards1) 93355333  selling...
1       Unregistered prepaid cards1) 93355888  selling...
2       Unregistered prepaid cards. Can port to post p...
3       Unregistered prepaid cards. Can port to post p...
4       PREORDER Takes about 23 weeks to arrive, will ...
...                                                   ...
464428  Type: Dress Gender: Womens Size Type: Regular ...
464429  Gender: For Women Item Type: Pendant Necklaces...
464430  Gender: For Women Item Type: Pendant Necklaces...
464431  Style: Active Length: Mini Material: Nylon,Pol...
464432  Style: Active Length: Mini Material: Nylon,Pol...

                                           item_variation  price  stock  \
0                                                      {}  400.0      1
1                                                      {}  400.0      1
2                                                      {}    8.0      1
3                                                      {}    8.0      1
4       {NEWERA BLACK: 35.0, NIKE SWOOSH DENIM: 35.0, ...   35.0    300
...                                                   ...    ...    ...
464428  {White S: 8.3, Black XL: 8.3, White XL: 8.3, B...    8.3      0
464429                                                 {}    0.6      0
464430                                                 {}    3.0      0
464431  {Purple: 2.0, Rose: 2.0, Sapphire blue: 3.0, B...    2.0      0
464432  {Purple: 4.0, Rose: 4.0, Sapphire blue: 4.0, B...    4.0      0

                       category  cb_option  is_preferred  sold_count  \
0              Mobile & Gadgets          0             0           0
1              Mobile & Gadgets          0             0           0
2              Mobile & Gadgets          0             0           0
3              Mobile & Gadgets          0             0           0
4               Women's Apparel          0             0           0
...                         ...        ...           ...         ...
464428          Women's Apparel          1             0           0
464429  Jewellery & Accessories          1             0           0
464430  Jewellery & Accessories          1             0           0
464431          Women's Apparel          1             0           1
464432          Women's Apparel          1             0           0

        item_creation_date
0      2015-10-01 00:24:42
1      2015-10-01 00:26:37
2      2015-08-25 21:02:13
3      2015-08-30 20:16:07
4      2016-05-09 01:14:34
...                    ...
464428 2017-09-24 18:42:46
464429 2017-09-15 21:10:15
464430 2017-09-17 09:07:06
464431 2017-05-14 11:46:53
464432 2017-06-20 21:48:26

[464433 rows x 12 columns]

In [ ]:
#how many unique shops are in the dataset
len(df.shopid.unique())

7856

In [ ]:
#how many unique preferred shops and cross border shops are in the dataset
len(df[df.is_preferred==1].shopid.unique())
# len(df[df[df.is_preferred==1] & [df.cb_option==1]].shopid.unique())
len(df[(df['is_preferred'] == 1) & (df['cb_option'] == 1)]['shopid'].unique())

158

In [ ]:
#number 3
df[(df.sold_count==0)]['itemid'].count()

len(df[df['sold_count']==0]['itemid'].unique())

438092

In [ ]:
#how many products were created in the yr 2018
df['item_creation_date'] = pandas.to_datetime(df['item_creation_date'])
df[df['item_creation_date'].dt.year == 2018]['itemid'].count()

177407

In [ ]:
#show top 3 preferred shops that have the largest number of unique products
df[(df.is_preferred==1)]['shopid'].value_counts()[:3]

shopid
43384791    2034
6072241     1998
26974701    1037
Name: count, dtype: int64

In [ ]:
#show top 3 categories that have the largest number of unique cross border items
df[(df.cb_option==1)]['category'].value_counts()[:3]

category
Women's Apparel     80494
Mobile & Gadgets    58760
Men's Wear          51795
Name: count, dtype: int64

In [ ]:
#find top 3 shopid with the highest revenue
revenue=df['price']*df['sold_count']
df['revenue']=revenue
df.groupby('shopid')['revenue'].sum().sort_values(ascending=False)[:3]

shopid
18796234    177897.79
30769353     63491.39
30628794     39852.00
Name: revenue, dtype: float64

In [ ]:
#find number of products with more than 3 variations
df['item_variation'].value_counts()[df['item_variation'].value_counts()>3]

item_variation
{}                                                                                                                                                                                                                                                                                               153146
{Size_L: 11.96, Size_M: 11.96, Size_XS: 11.96, Size_XXL: 11.96, Size_3XL: 11.96, Size_XL: 11.96, Size_S: 11.96}                                                                                                                                                                                    4775
{Remark Color: 6.9, XL: 6.9, M: 6.9, L: 6.9, S: 6.9, XXL: 6.9}                                                                                                                                                                                                                                     3291
{Size_L: 12.59, Size_M: 12.59, Size_XS: 12.59, Size_XXL: 12.59, Size_3XL: 12.59, Size_XL: 12.59, Size_S: 12.59}                                                                                                                                                                                    2815
{Remark Color: 5.9, XL: 5.9, M: 5.9, L: 5.9, S: 5.9, XXL: 5.9}                                                                                                                                                                                                                                     2673
                                                                                                                                                                                                                                                                                                  ...
{Purple 32E: 24.22, Purple 40C: 24.22, Purple 40D: 24.22, Purple 32D: 24.22, Purple 34D: 24.22, Purple 34C: 24.22, Purple 34B: 24.22, Purple 38D: 24.22, Purple 38C: 24.22, Purple 38B: 24.22, Purple 32C: 24.22, Purple 32B: 24.22, Purple 36C: 24.22, Purple 36B: 24.22, Purple 36D: 24.22}         4
{Black 34: 23.0, Black 32: 23.0, Black 33: 23.0, Black 30: 23.0, Black 31: 23.0, Black 29: 23.0, Black 28: 23.0}                                                                                                                                                                                      4
{18CM*8CM: 15.0}                                                                                                                                                                                                                                                                                      4
{Black: 3.2}                                                                                                                                                                                                                                                                                          4
{简约款-土豪金★送钢化膜: 6.05, 简约款-深海蓝★送钢化膜: 6.05, 简约款-炫酷黑★送钢化膜: 6.05, 支架款-炫酷黑★送钢化膜: 7.45, 简约款-玫瑰金★送钢化膜: 6.05, 支架款-土豪金★送钢化膜: 7.45, 支架款-玫瑰金★送钢化膜: 7.45, 简约款-新年红★送钢化膜: 6.05, 支架款-新年红★送钢化膜: 7.45, 支架款-深海蓝★送钢化膜: 7.45}                                                                                              4
Name: count, Length: 6090, dtype: int64

In [ ]:
#identify duplicated listings within each shop(uif listing a and b have exactly same product title,product detailed description,and price, both listing a and b are considered duplicated)
are_duplicated = df.duplicated('item_name')
df[are_duplicated]

,itemid,shopid,item_name,item_description,item_variation,price,stock,category,cb_option,is_preferred,sold_count,item_creation_date
1,1925617,210000,Golden mobile numbers,Unregistered prepaid cards1) 93355888 selling...,{},400.00,1,Mobile & Gadgets,0,0,0,2015-10-01 00:26:37
3,1064405,210000,Golden Mobile Numbers,Unregistered prepaid cards. Can port to post p...,{},8.00,1,Mobile & Gadgets,0,0,0,2015-08-30 20:16:07
5,20047128,760000,101% AUTHENTIC BASEBALL CAPS,"PREORDER Takes about 23 weeks to arrive, will ...","{NIKE SWOOSH DENIM: 35.0, NIKE SWOOSH BLACK: 3...",35.00,299,Men's Wear,0,0,1,2016-05-09 01:18:21
7,252736983,11272000,Hada Labo Super Hydrating Perfect Gel Moisturi...,Hada Labo is a skin care line researched & dev...,{},28.72,8,Health & Beauty,0,1,1,2017-05-09 18:33:30
9,809446063,49082000,Women Lace Bra Bustier Crop Tops Soft Mesh Tri...,Material: Terylene Colors: BalckStyle: Sexy Br...,"{S: 9.98, M: 9.98, L: 9.98}",9.98,300,Women's Apparel,1,0,0,2018-01-05 16:08:24
...,...,...,...,...,...,...,...,...,...,...,...,...
464424,314601343,13744999,Cute Flower Sleeveless Mesh Baby Girls Dress,Style: Cute Material: Cotton Fabric Type: Broa...,"{9 Month: 7.57, 12 Month: 7.57, 24 Month: 7.57...",7.57,0,"Toys, Kids & Babies",1,0,0,2017-06-20 23:06:49
464426,314558797,13744999,Babies Beanie Hat Han Edition Cotton Letter Pr...,Gender: Unisex Item Type: Baby Hat Material: C...,"{Grey + I love mama: 3.0, White + I love papa:...",3.00,0,"Toys, Kids & Babies",1,0,0,2017-06-20 21:48:25
464428,517929442,13744999,Women Back Brest Dress Package Hips Dress,Type: Dress Gender: Womens Size Type: Regular ...,"{White S: 8.3, Black XL: 8.3, White XL: 8.3, B...",8.30,0,Women's Apparel,1,0,0,2017-09-24 18:42:46
464430,494272761,13744999,Heart Alloy Pendant Necklace for women,Gender: For Women Item Type: Pendant Necklaces...,{},3.00,0,Jewellery & Accessories,1,0,0,2017-09-17 09:07:06
464432,314558812,13744999,Women Mid Elastic Waist Straight Shorts,"Style: Active Length: Mini Material: Nylon,Pol...","{Purple: 4.0, Rose: 4.0, Sapphire blue: 4.0, B...",4.00,0,Women's Apparel,1,0,0,2017-06-20 21:48:26

In [ ]:
import numpy as np
np.arange(0,456577)

array([     0,      1,      2, ..., 456574, 456575, 456576])

In [ ]:
#mark these listings with True otherwise False and store the marking results in a new column called is_duplicated
df['is_duplicated']=are_duplicated
df

,itemid,shopid,item_name,item_description,item_variation,price,stock,category,cb_option,is_preferred,sold_count,item_creation_date,is_duplicated
0,1925574,210000,Golden mobile numbers,Unregistered prepaid cards1) 93355333 selling...,{},400.0,1,Mobile & Gadgets,0,0,0,2015-10-01 00:24:42,False
1,1925617,210000,Golden mobile numbers,Unregistered prepaid cards1) 93355888 selling...,{},400.0,1,Mobile & Gadgets,0,0,0,2015-10-01 00:26:37,True
2,943600,210000,Golden Mobile Numbers,Unregistered prepaid cards. Can port to post p...,{},8.0,1,Mobile & Gadgets,0,0,0,2015-08-25 21:02:13,False
3,1064405,210000,Golden Mobile Numbers,Unregistered prepaid cards. Can port to post p...,{},8.0,1,Mobile & Gadgets,0,0,0,2015-08-30 20:16:07,True
4,20046620,760000,101% AUTHENTIC BASEBALL CAPS,"PREORDER Takes about 23 weeks to arrive, will ...","{NEWERA BLACK: 35.0, NIKE SWOOSH DENIM: 35.0, ...",35.0,300,Women's Apparel,0,0,0,2016-05-09 01:14:34,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
464428,517929442,13744999,Women Back Brest Dress Package Hips Dress,Type: Dress Gender: Womens Size Type: Regular ...,"{White S: 8.3, Black XL: 8.3, White XL: 8.3, B...",8.3,0,Women's Apparel,1,0,0,2017-09-24 18:42:46,True
464429,490461243,13744999,Heart Alloy Pendant Necklace for women,Gender: For Women Item Type: Pendant Necklaces...,{},0.6,0,Jewellery & Accessories,1,0,0,2017-09-15 21:10:15,False
464430,494272761,13744999,Heart Alloy Pendant Necklace for women,Gender: For Women Item Type: Pendant Necklaces...,{},3.0,0,Jewellery & Accessories,1,0,0,2017-09-17 09:07:06,True
464431,259494170,13744999,Women Mid Elastic Waist Straight Shorts,"Style: Active Length: Mini Material: Nylon,Pol...","{Purple: 2.0, Rose: 2.0, Sapphire blue: 3.0, B...",2.0,0,Women's Apparel,1,0,1,2017-05-14 11:46:53,False
464432,314558812,13744999,Women Mid Elastic Waist Straight Shorts,"Style: Active Length: Mini Material: Nylon,Pol...","{Purple: 4.0, Rose: 4.0, Sapphire blue: 4.0, B...",4.0,0,Women's Apparel,1,0,0,2017-06-20 21:48:26,True

In [ ]:
#find duplicate listings that has less than 2 sold count and store the results in a new excel file named "duplicated_listings.xlsx"
filtered_df = df[(df.is_duplicated==True) & (df.sold_count<2)]
filtered_df.to_excel("duplicated_listings.xlsx", index=False)

In [ ]:
#find the preferred shop shopid that have the most number of duplicated listings

df[(duplicated_listings.xlsx==1)]['shopid'].value_counts()

NameError: name 'duplicated_listings' is not defined